In [24]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')

In [25]:
df = pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [26]:
df.isnull().sum()


age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [27]:
#Removing duplicated values
df = df.loc[~df.duplicated()].copy()

* More EDA is required to understand the relationship between the features

## Data is ready for modeling

In [28]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [29]:
# breaking deoendent and independet varaiable
x = df[['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal']]
y = df['target']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.30, random_state=101)

## Logistic Regression Model

In [32]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()

In [33]:
logmodel.fit(x_train,y_train)

/home/rohan/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [34]:
#Cheking prediction of the model 
prediction = logmodel.predict(x_test)
prediction

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0])

In [35]:
prediction_df = pd.DataFrame(prediction,columns=["target_predicted"])
prediction_df

target_predicted
0                  0
1                  0
2                  1
3                  0
4                  1
..               ...
86                 0
87                 1
88                 0
89                 0
90                 0

[91 rows x 1 columns]

In [36]:
#Testing model accuracy
from sklearn.metrics import confusion_matrix

In [37]:
accuracy = confusion_matrix(y_test,prediction)
accuracy

array([[30,  9],
       [ 8, 44]])

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy = accuracy_score(y_test,prediction)
accuracy

0.8131868131868132

## Decision Tree Model

In [40]:
from sklearn.tree import DecisionTreeClassifier
dtmodel = DecisionTreeClassifier()

In [41]:
dtmodel.fit(x_train,y_train)

DecisionTreeClassifier()

In [42]:
#predicttion with decison tree model
prediction = dtmodel.predict(x_test)
prediction

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0])

In [43]:
#Testing the accuracy of the model 
from sklearn.metrics import confusion_matrix

In [44]:
accuracy = confusion_matrix(prediction,y_test)
accuracy

array([[27, 11],
       [12, 41]])

In [45]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(prediction,y_test)
accuracy

0.7472527472527473

## Random Forest Model

In [46]:
from sklearn.ensemble import RandomForestClassifier
rfclass = RandomForestClassifier()

In [47]:
rfclass.fit(x_train,y_train)

RandomForestClassifier()

In [48]:
prediction = rfclass.predict(x_test)
prediction

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0])

In [49]:
#testing accuracy of the model
from sklearn.metrics import confusion_matrix

In [50]:
accuracy = confusion_matrix(prediction,y_test)
accuracy

array([[29,  9],
       [10, 43]])

In [51]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(prediction,y_test)
accuracy

0.7912087912087912

## xgboost model

In [52]:
from sklearn.ensemble import GradientBoostingClassifier
xgboost = GradientBoostingClassifier()

In [53]:
xgboost.fit(x_train,y_train)

GradientBoostingClassifier()

In [54]:
prediction = xgboost.predict(x_test)
prediction

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0])

In [55]:
#Accuracy of the model
from sklearn.metrics import confusion_matrix

In [56]:
accuracy = confusion_matrix(prediction,y_test)
accuracy

array([[29, 10],
       [10, 42]])

In [57]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(prediction,y_test)
accuracy

0.7802197802197802